### ISSUE TITLE
Failover implemented?

### ISSUE THREAD

**Issue by onham** [arianitu/postgres-statefulset#2] opened 2019-07-29 15:39 UTC
Replication works - however for the replica, having 'standby = on' does not actually have it be promoted as the master in the case of failure of the master db pod. Has failover ever been tested with this setup?

**Comment by arianitu** [comment] 2019-08-26 12:19
Hello @onham, just noticed this issue was opened. We have not tested failover on our system. Reading the documentation at https://www.postgresql.org/docs/9.6/warm-standby-failover.html it does not appear Postgres supports detecting master failure and you may have to promote a replica your self?

If you wanted to test, you can scale the master statefulset to 0 and see what happens:

`kubectl scale statefulset postgres--replicas=0`

**Comment by arianitu** [comment] 2019-08-26 12:21
@onham confirmed from https://wiki.postgresql.org/wiki/Streaming_Replication that failover is done manually via a trigger file, refer to the wiki.

since this is a manual process, we can't really support it so I'll close this for now unless you think there's a good way to do it.

**Closed as completed by arianitu** 2019-08-26 12:21 UTC
